version: '3.8'

services:

  db:
    container_name: postgresql_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: kaschenko/prosept_backend:v1
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: kaschenko/prosept_front:v3
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: frontend

  nginx:
    container_name: nginx
    image: nginx:1.21.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

volumes:
  database: