"""Initial migration

Revision ID: 169ce6523b2f
Revises: b9a24f3775e8
Create Date: 2023-11-30 10:45:19.763504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169ce6523b2f'
down_revision: Union[str, None] = 'b9a24f3775e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_product_dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_ids', sa.ARRAY(sa.Integer()), nullable=True, comment='Пять ID товаров от Просепт'),
    sa.Column('dealerprice_id', sa.Integer(), nullable=True, comment='ID товара от диллера'),
    sa.ForeignKeyConstraint(['dealerprice_id'], ['marketing_dealerprice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_product_dealer_id'), 'matching_product_dealer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_product_dealer_id'), table_name='matching_product_dealer')
    op.drop_table('matching_product_dealer')
    # ### end Alembic commands ###
