"""Initial migration

Revision ID: b9a24f3775e8
Revises: 
Create Date: 2023-11-29 18:31:30.101472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a24f3775e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_dealer_id'), 'marketing_dealer', ['id'], unique=False)
    op.create_table('marketing_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.Integer(), nullable=True, comment='артикул товара'),
    sa.Column('ean_13', sa.String(), nullable=True, comment='код товара'),
    sa.Column('cost', sa.Float(), nullable=True, comment='стоимость'),
    sa.Column('name', sa.String(), nullable=True, comment='название товара'),
    sa.Column('min_recommended_price', sa.Float(), nullable=True, comment='рекомендованная минимальная цена'),
    sa.Column('recommended_price', sa.Float(), nullable=True, comment='рекомендованная цена'),
    sa.Column('category_id', sa.String(), nullable=True, comment='категория товара'),
    sa.Column('ozon_name', sa.String(), nullable=True, comment='названиет товара на Озоне'),
    sa.Column('name_1c', sa.String(), nullable=True, comment='название товара в 1C'),
    sa.Column('wb_name', sa.String(), nullable=True, comment='название товара на Wildberries'),
    sa.Column('ozon_article', sa.String(), nullable=True, comment='описание для Озон'),
    sa.Column('wb_article', sa.String(), nullable=True, comment='артикул для Wildberries'),
    sa.Column('ym_article', sa.String(), nullable=True, comment='артикул для Яндекс.Маркета'),
    sa.Column('wb_article_td', sa.String(), nullable=True, comment='артикул для Wildberries td'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_product_id'), 'marketing_product', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('marketing_dealerprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(), nullable=True, comment='уникальный номер позиции'),
    sa.Column('price', sa.Float(), nullable=True, comment='цена'),
    sa.Column('product_url', sa.String(), nullable=True, comment='адрес страницы, откуда собраны данные'),
    sa.Column('product_name', sa.String(), nullable=True, comment='заголовок продаваемого товара'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='дата получения информации'),
    sa.Column('dealer_id', sa.Integer(), nullable=True, comment='идентификатор дилера'),
    sa.ForeignKeyConstraint(['dealer_id'], ['marketing_dealer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_key')
    )
    op.create_index(op.f('ix_marketing_dealerprice_id'), 'marketing_dealerprice', ['id'], unique=False)
    op.create_table('marketing_productdealerkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['marketing_dealer.id'], ),
    sa.ForeignKeyConstraint(['key'], ['marketing_dealerprice.product_key'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketing_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_productdealerkey')
    op.drop_index(op.f('ix_marketing_dealerprice_id'), table_name='marketing_dealerprice')
    op.drop_table('marketing_dealerprice')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_marketing_product_id'), table_name='marketing_product')
    op.drop_table('marketing_product')
    op.drop_index(op.f('ix_marketing_dealer_id'), table_name='marketing_dealer')
    op.drop_table('marketing_dealer')
    # ### end Alembic commands ###
